



namespace SourceGenerator.Basic
{
    [Generator("C#")]
    public class GreetingGenerator : ISourceGenerator
    {
       
        public void Execute(GeneratorExecutionContext context)
        {
            context.AddSource(
                "Greeting.g.cs",
                $$"""
                //告知编译器，该文件由源代码生成器或别的手段生成的代码
                //<auto-generated/>
                //启用可空性检查。为C# 8 提供特性
                #nullable enable
                namespace GreetingTest;

                
               
                [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("{{nameof(GreetingGenerator)}}","1.0")]
                public static class Greeting
                {
                    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
                    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("{{nameof(GreetingGenerator)}}","1.0")]
                    public static void SayHelloTo(string name)
                    =>global::System.Console.WriteLine($"Hello {name}");
                }
                """
                );
        }

        public void Initialize(GeneratorInitializationContext context)
        {
            
        }
    }
}
